// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table Counter_raw (Data:dynamic) 
.alter table Counter_raw policy retention @'{"SoftDeletePeriod":"7.00:00:00","Recoverability":"Disabled"}'
.alter table Counter_raw policy streamingingestion "{\"IsEnabled\":true,\"HintAllocatedRate\":null,\"NumberOfRowStores\":null,\"SealIntervalLimit\":null,\"SealThresholdBytes\":null,\"UsageTags\":[],\"IsMaintenanceActive\":false}"
